DQN v2 Rewards & Algorithm Changes
BoundlessDevelopment/Capstone-Project pull request #58
Opened 2024-03-20 23:14 UTC by Thanoshan

This PR merges in the changes that enable our DQN v2 Flagship Algorithm. We also have changes to the reward functions including, individualized feedback, delta rewards and time penalty rewards.

2024-03-29 17:02 UTC, pandyah5 requested changes
LGTM overall, I have left a few comments on specific sections

2024-03-30 22:02 UTC, Thanoshan commented on src/nepiada/rl_ma_dqn_experimental.py
> +        # curr_epsilon = worker.policy_map["parameter_sharing"].get_exploration_state()["cur_epsilon"]
Yeah you would need this if you do parameter sharing, I'd keep this in.

2024-03-30 22:03 UTC, Thanoshan commented on src/nepiada/rl_ma_dqn_experimental.py
> +    config = config.rollouts(num_rollout_workers=0, rollout_fragment_length=100, compress_observations=True)
Yeah you need multiple workers for sure for training, I like to use no rollout workers during demo/testing thourhg post training cause you don't need samplers. I'd leave it at 0 and we can change it to whatever on our own end depending on our system specs.

2024-03-30 22:06 UTC, Thanoshan commented on src/nepiada/env/nepiada.py
> +            rewards[agent_name] = curr_scores[agent_name] - self.world.agents[agent_name].prev_score
Done.

2024-03-30 22:07 UTC, Thanoshan commented on src/nepiada/env/nepiada.py
> +                if rewards[agent_name] < 0:
You're right, this would not be triggered ever. IT was a relic of an older function I was trying. Removed it.

2024-03-30 22:08 UTC, pandyah5 approved these changes

2024-03-30 22:08 UTC, merged